version: "3.6"
services:
  postgres:
    image: postgres:12
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  worker:
    build:
      context: .
    stop_grace_period: 10m
    restart: always
    depends_on:
      - postgres
    environment:
      POSTGRES_CONNECTION: postgres://postgres:password@postgres:5432/postgres?sslmode=disable
      GITHUB_RATE_LIMIT: 1/2
    env_file:
      - .env-worker
    ports:
      - 3301:8080

  graphql:
    restart: always
    build:
      context: ./graphql
    depends_on:
      - postgres
    ports:
      - 5433:5433
    command:
      - "--connection"
      - "postgres://postgres:password@postgres:5432/postgres?sslmode=disable"
      - "--port"
      - "5433"
      - "--schema"
      - "mergestat,public"
      - "--append-plugins"
      - "@graphile-contrib/pg-simplify-inflector"
      - "-o"
      - "--subscriptions"
      - "--retry-on-init-fail"
      - "--dynamic-json"
      - "--no-setof-functions-contain-nulls"
      - "--no-ignore-rbac"
      - "--extended-errors=errcode"
      - "--disable-graphiql"
      - "--enable-query-batching"
      - "--disable-query-log"
      - "--legacy-relations=omit"

  ui:
    restart: always
    build:
      context: ./ui
    depends_on:
      - graphql
    ports:
      - 3300:3000    

  grafana:
    image: grafana/grafana-oss:latest
    environment:
      PGHOST: postgres
      PGUSER: postgres
      PGPASSWORD: password
      PGDATABASE: postgres
    ports:
      - 3000:3000
    depends_on:
      - postgres
    restart: always
    volumes:
      - grafana_lib:/var/lib/grafana
      - grafana_etc:/etc/grafana
      - grafana_log:/var/log/grafana
      - ./scripts/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./scripts/grafana/provisioning:/etc/grafana/provisioning
      - ./scripts/grafana/dashboards:/var/lib/grafana/dashboards/

volumes:
  db_data:
  grafana_lib:
  grafana_etc:
  grafana_log:
